[package]
name = "ethereum_evm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
ethnum = "1.5.0"
keccak-hash = "0.10.0"
test_gen = { path = "./test_gen" }
