[package]
name = "test_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.35"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.114"
syn = "2.0.52"

[lib]
proc-macro = true
